// config/thresholds.ts
export const THRESHOLDS = {
  OPPORTUNITY_WEIGHT_HARD_CEILING: 0.15,
  ENGINE_BONUS_CAP: 15,
  ENGINE_PENALTY_CAP: 40,
  HYBRID_RANKING_BONUS_CAP: 15,
  HYBRID_RANKING_PENALTY_CAP: 40,
  TIE_BREAK_DIFFERENCE: 0.5,
  EXCELLENT_MATCH_MIN: 90,
  STRONG_MATCH_MIN: 80,
  GOOD_MATCH_MIN: 70,
  MODERATE_MATCH_MIN: 60,
  CONFIDENCE_LOW_THRESHOLD: 60,
};
